/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as Sitemap_indexDotxmlRouteImport } from './routes/sitemap_index[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapIndexDotxmlRouteImport } from './routes/sitemap-index[.]xml'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LatestRouteImport } from './routes/latest'
import { Route as FeaturedRouteImport } from './routes/featured'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdminApplicationsRouteImport } from './routes/admin-applications'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GenreSlugRouteImport } from './routes/genre.$slug'
import { Route as ComicComicIdRouteImport } from './routes/comic.$comicId'
import { Route as BlogTop10GravureIdols2024RouteImport } from './routes/blog.top-10-gravure-idols-2024'
import { Route as BlogGravureIdolLaGiRouteImport } from './routes/blog.gravure-idol-la-gi'
import { Route as ApiDriveFileRouteImport } from './routes/api/drive-file'
import { Route as ReadComicIdChapterIdRouteImport } from './routes/read.$comicId.$chapterId'
import { Route as ApiPublicPlisioCallbackRouteImport } from './routes/api/public/plisio/callback'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const Sitemap_indexDotxmlRoute = Sitemap_indexDotxmlRouteImport.update({
  id: '/sitemap_index.xml',
  path: '/sitemap_index.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapIndexDotxmlRoute = SitemapIndexDotxmlRouteImport.update({
  id: '/sitemap-index.xml',
  path: '/sitemap-index.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LatestRoute = LatestRouteImport.update({
  id: '/latest',
  path: '/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturedRoute = FeaturedRouteImport.update({
  id: '/featured',
  path: '/featured',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/admin-applications',
  path: '/admin-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenreSlugRoute = GenreSlugRouteImport.update({
  id: '/genre/$slug',
  path: '/genre/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ComicComicIdRoute = ComicComicIdRouteImport.update({
  id: '/comic/$comicId',
  path: '/comic/$comicId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogTop10GravureIdols2024Route =
  BlogTop10GravureIdols2024RouteImport.update({
    id: '/blog/top-10-gravure-idols-2024',
    path: '/blog/top-10-gravure-idols-2024',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogGravureIdolLaGiRoute = BlogGravureIdolLaGiRouteImport.update({
  id: '/blog/gravure-idol-la-gi',
  path: '/blog/gravure-idol-la-gi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriveFileRoute = ApiDriveFileRouteImport.update({
  id: '/api/drive-file',
  path: '/api/drive-file',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadComicIdChapterIdRoute = ReadComicIdChapterIdRouteImport.update({
  id: '/read/$comicId/$chapterId',
  path: '/read/$comicId/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlisioCallbackRoute = ApiPublicPlisioCallbackRouteImport.update({
  id: '/api/public/plisio/callback',
  path: '/api/public/plisio/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-applications': typeof AdminApplicationsRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/featured': typeof FeaturedRoute
  '/latest': typeof LatestRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signin': typeof SigninRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sitemap_index.xml': typeof Sitemap_indexDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/drive-file': typeof ApiDriveFileRoute
  '/blog/gravure-idol-la-gi': typeof BlogGravureIdolLaGiRoute
  '/blog/top-10-gravure-idols-2024': typeof BlogTop10GravureIdols2024Route
  '/comic/$comicId': typeof ComicComicIdRoute
  '/genre/$slug': typeof GenreSlugRoute
  '/read/$comicId/$chapterId': typeof ReadComicIdChapterIdRoute
  '/api/public/plisio/callback': typeof ApiPublicPlisioCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-applications': typeof AdminApplicationsRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/featured': typeof FeaturedRoute
  '/latest': typeof LatestRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signin': typeof SigninRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sitemap_index.xml': typeof Sitemap_indexDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/drive-file': typeof ApiDriveFileRoute
  '/blog/gravure-idol-la-gi': typeof BlogGravureIdolLaGiRoute
  '/blog/top-10-gravure-idols-2024': typeof BlogTop10GravureIdols2024Route
  '/comic/$comicId': typeof ComicComicIdRoute
  '/genre/$slug': typeof GenreSlugRoute
  '/read/$comicId/$chapterId': typeof ReadComicIdChapterIdRoute
  '/api/public/plisio/callback': typeof ApiPublicPlisioCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-applications': typeof AdminApplicationsRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/featured': typeof FeaturedRoute
  '/latest': typeof LatestRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signin': typeof SigninRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sitemap_index.xml': typeof Sitemap_indexDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/drive-file': typeof ApiDriveFileRoute
  '/blog/gravure-idol-la-gi': typeof BlogGravureIdolLaGiRoute
  '/blog/top-10-gravure-idols-2024': typeof BlogTop10GravureIdols2024Route
  '/comic/$comicId': typeof ComicComicIdRoute
  '/genre/$slug': typeof GenreSlugRoute
  '/read/$comicId/$chapterId': typeof ReadComicIdChapterIdRoute
  '/api/public/plisio/callback': typeof ApiPublicPlisioCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-applications'
    | '/apply'
    | '/contact'
    | '/featured'
    | '/latest'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/robots.txt'
    | '/signin'
    | '/sitemap-index.xml'
    | '/sitemap.xml'
    | '/sitemap_index.xml'
    | '/terms'
    | '/api/drive-file'
    | '/blog/gravure-idol-la-gi'
    | '/blog/top-10-gravure-idols-2024'
    | '/comic/$comicId'
    | '/genre/$slug'
    | '/read/$comicId/$chapterId'
    | '/api/public/plisio/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-applications'
    | '/apply'
    | '/contact'
    | '/featured'
    | '/latest'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/robots.txt'
    | '/signin'
    | '/sitemap-index.xml'
    | '/sitemap.xml'
    | '/sitemap_index.xml'
    | '/terms'
    | '/api/drive-file'
    | '/blog/gravure-idol-la-gi'
    | '/blog/top-10-gravure-idols-2024'
    | '/comic/$comicId'
    | '/genre/$slug'
    | '/read/$comicId/$chapterId'
    | '/api/public/plisio/callback'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admin-applications'
    | '/apply'
    | '/contact'
    | '/featured'
    | '/latest'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/robots.txt'
    | '/signin'
    | '/sitemap-index.xml'
    | '/sitemap.xml'
    | '/sitemap_index.xml'
    | '/terms'
    | '/api/drive-file'
    | '/blog/gravure-idol-la-gi'
    | '/blog/top-10-gravure-idols-2024'
    | '/comic/$comicId'
    | '/genre/$slug'
    | '/read/$comicId/$chapterId'
    | '/api/public/plisio/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  ApplyRoute: typeof ApplyRoute
  ContactRoute: typeof ContactRoute
  FeaturedRoute: typeof FeaturedRoute
  LatestRoute: typeof LatestRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SigninRoute: typeof SigninRoute
  SitemapIndexDotxmlRoute: typeof SitemapIndexDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Sitemap_indexDotxmlRoute: typeof Sitemap_indexDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiDriveFileRoute: typeof ApiDriveFileRoute
  BlogGravureIdolLaGiRoute: typeof BlogGravureIdolLaGiRoute
  BlogTop10GravureIdols2024Route: typeof BlogTop10GravureIdols2024Route
  ComicComicIdRoute: typeof ComicComicIdRoute
  GenreSlugRoute: typeof GenreSlugRoute
  ReadComicIdChapterIdRoute: typeof ReadComicIdChapterIdRoute
  ApiPublicPlisioCallbackRoute: typeof ApiPublicPlisioCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap_index.xml': {
      id: '/sitemap_index.xml'
      path: '/sitemap_index.xml'
      fullPath: '/sitemap_index.xml'
      preLoaderRoute: typeof Sitemap_indexDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-index.xml': {
      id: '/sitemap-index.xml'
      path: '/sitemap-index.xml'
      fullPath: '/sitemap-index.xml'
      preLoaderRoute: typeof SitemapIndexDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latest': {
      id: '/latest'
      path: '/latest'
      fullPath: '/latest'
      preLoaderRoute: typeof LatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/featured': {
      id: '/featured'
      path: '/featured'
      fullPath: '/featured'
      preLoaderRoute: typeof FeaturedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-applications': {
      id: '/admin-applications'
      path: '/admin-applications'
      fullPath: '/admin-applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genre/$slug': {
      id: '/genre/$slug'
      path: '/genre/$slug'
      fullPath: '/genre/$slug'
      preLoaderRoute: typeof GenreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comic/$comicId': {
      id: '/comic/$comicId'
      path: '/comic/$comicId'
      fullPath: '/comic/$comicId'
      preLoaderRoute: typeof ComicComicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/top-10-gravure-idols-2024': {
      id: '/blog/top-10-gravure-idols-2024'
      path: '/blog/top-10-gravure-idols-2024'
      fullPath: '/blog/top-10-gravure-idols-2024'
      preLoaderRoute: typeof BlogTop10GravureIdols2024RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/gravure-idol-la-gi': {
      id: '/blog/gravure-idol-la-gi'
      path: '/blog/gravure-idol-la-gi'
      fullPath: '/blog/gravure-idol-la-gi'
      preLoaderRoute: typeof BlogGravureIdolLaGiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drive-file': {
      id: '/api/drive-file'
      path: '/api/drive-file'
      fullPath: '/api/drive-file'
      preLoaderRoute: typeof ApiDriveFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$comicId/$chapterId': {
      id: '/read/$comicId/$chapterId'
      path: '/read/$comicId/$chapterId'
      fullPath: '/read/$comicId/$chapterId'
      preLoaderRoute: typeof ReadComicIdChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plisio/callback': {
      id: '/api/public/plisio/callback'
      path: '/api/public/plisio/callback'
      fullPath: '/api/public/plisio/callback'
      preLoaderRoute: typeof ApiPublicPlisioCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  ApplyRoute: ApplyRoute,
  ContactRoute: ContactRoute,
  FeaturedRoute: FeaturedRoute,
  LatestRoute: LatestRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SigninRoute: SigninRoute,
  SitemapIndexDotxmlRoute: SitemapIndexDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Sitemap_indexDotxmlRoute: Sitemap_indexDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiDriveFileRoute: ApiDriveFileRoute,
  BlogGravureIdolLaGiRoute: BlogGravureIdolLaGiRoute,
  BlogTop10GravureIdols2024Route: BlogTop10GravureIdols2024Route,
  ComicComicIdRoute: ComicComicIdRoute,
  GenreSlugRoute: GenreSlugRoute,
  ReadComicIdChapterIdRoute: ReadComicIdChapterIdRoute,
  ApiPublicPlisioCallbackRoute: ApiPublicPlisioCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
